src/config/routes.rb
Rails.application.routes.draw do
  get 'configuration/index'

  devise_for :users

  get '/users/approve/:id', to: 'users#toggle_approve', as: :toggle_approve_user
  get '/users/removable/:id', to: 'users#toggle_removable', as: :toggle_removable_user

  resources 'users'

  namespace :test_server do
    get 'file_downloads/by-label/:label', to: 'file_downloads#by_label', as: 'file_downloads_by_label'

    resources :file_downloads

    resources :meta_information, only: %i(index)

    namespace :active_content do
      get :javascript, to: 'javascript#show'
    end
    get :active_content, to: 'active_content#index'

    namespace :dns_requests do
      resources :host_name, only: %i(new create)
      resources :ip_address, only: %i(new create)
    end

    namespace :reflectors do
      get :request_headers, to: 'request_headers#show'
      post :request_body, to: 'request_body#create'
      get :request_body, to: 'request_body#show'
      get :client_ip_address, to: 'client_ip_address#show'
      get :params, to: 'params#show'
    end

    get :reflectors, to: 'reflectors#index'

    namespace :streaming do
      get :plain, to: 'plain#show'
      get :eicar, to: 'eicar#show'
      get :random, to: 'random#show'
    end

    get :streaming, to: 'streaming#index'

    namespace :string do
      get :plain, to: 'plain#show'
      get :eicar, to: 'eicar#show'
      get :random, to: 'random#show'
      get :sleep, to: 'sleep#show'
    end

    get :string, to: 'string#index'

    namespace :file_uploader do
      get :upload, to: 'upload#new'
      post :upload, to: 'upload#create'
    end

    get :file_uploader, to: 'file_uploader#index'

    namespace :generator do
      get :xhr, to: 'xhr#show', format: false
    end

    get :generator, to: 'generator#index'

    resources :whois_requests, only: %i(new create)
  end

  scope module: 'test_server' do
    root 'dashboard#show'

    get '/dashboard', to: 'dashboard#show'
    get '/static', to: 'static#index'
  end

end

src/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable, :timeoutable
  # devise :database_authenticatable, :trackable, :timeoutable
  devise :database_authenticatable, :trackable
  belongs_to :role

  has_many :file_downloads, class_name: 'TestServer::FileDownload'

  before_create :set_default_role
  scope :all_but_anonymous, ->{ User.where.not(email: 'anonymous') }

  def role?(r)
    role.name.to_sym == r.to_sym
  end

  def toggle_approve
    if approved?
      self.approved = false
    else
      self.approved = true
    end

  end

  def toggle_removable
    if removable?
      self.removable = false
    else
      self.removable = true
    end
  end

  def removable?
    removable == true
  end

  def approved?
    approved == true
  end

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved? 
      :not_approved 
    else
      super # Use whatever other message 
    end
  end

  private

  def set_default_role
    self.role ||= Role.find_by_name('user')
  end
end

src/app/controllers/users_controller.rb
require 'test_server/permitted_params/users_parameter_sanitizer'

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :destroy, :update, :toggle_approve, :toggle_removable]

  add_breadcrumb I18n.t('views.root.link'), :root_path
  add_breadcrumb I18n.t('views.users.link'), :users_path

  before_action :authenticate_user!

  # GET /users
  def index
    authorize User
    @users = User.all_but_anonymous
  end

  # GET /users/1
  def show
    add_breadcrumb @user.email
  end

  # GET /users/new
  def new
    @user = User.new
    authorize @user
  end

  # GET /users/1/edit
  def edit
  end

  def toggle_approve
    fail 'Cannot unapprove last admin user' if @user.role.name == 'admin' && @user.approved? && User.joins(:role).where(roles: { name: 'admin'}).count < 2
    fail 'Cannot modify anonymous' if @user.email == 'anonymous'

    authorize @user
    @user.toggle_approve
    @user.save!

    redirect_to request.referrer
  end

  def toggle_removable
    fail 'Cannot modify anonymous' if @user.email == 'anonymous'

    authorize @user
    @user.toggle_removable
    @user.save!

    redirect_to request.referrer
  end

  # POST /users
  def create
    @user = User.new(user_params)
    authorize @user
    @user.save!

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  def destroy
    fail 'Cannot delete last admin user' if @user.role.name == 'admin' && User.joins(:role).where(roles: { name: 'admin'}).count < 2

    null_user = User.where(email: 'anonymous').first
    files = @user.file_downloads.all
    files.each do |f|
      f.user = null_user
      f.save!
    end

    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    parameter_sanitizer.use(
      params
    ).fetch(:user, {})
  end

  def parameter_sanitizer
    TestServer::PermittedParams::UsersParameterSanitizer.new
  end
end

src/app/helpers/users_helper.rb
module UsersHelper
end

src/app/views/users/_form.html.haml
= form_for @user, html: { multipart: true, id: :form, class: :'ts-form' } do |form|
  .ts-form-group
    = form.label :email
    = form.text_field :email, class: 'ts-field-label'
  .ts-form-group
    = form.label :password
    = form.password_field :password, class: 'ts-field-label', autocomplete: :off, required: true
  .ts-form-group
    = form.label :role
    = form.collection_select :role_id, Role.all, :id, :name
  = form.submit t('views.application.buttons.save'), id: :save, class: 'ts-button-upload', name: :save
  %a#reset.ts-button-reset{href: '#', name: 'reset'}
    = t('views.application.buttons.reset')
  = link_to t('views.application.buttons.cancel'), users_path, class: 'ts-button-cancel', name: 'cancel'

src/app/views/users/edit.html.haml
%h1
  = User.model_name.human
= render 'form'

src/app/views/users/index.html.haml
%h1
  = t('views.users.index.title')

= link_to t('views.users.new.link'), new_user_path,  class: 'ts-button-new'

%table.ts-data-table
  %thead
    %tr
      %th.ts-data-column-75
        = User.human_attribute_name(:email)
      %th.ts-data-column-75
        = User.human_attribute_name(:approved)
      - %i(sign_in_count current_sign_in_at last_sign_in_at current_sign_in_ip last_sign_in_ip created_at updated_at).each do |attribute|
        %th.ts-data-column-100
          = User.human_attribute_name(attribute)
      %th.ts-data-column-35
        = User.human_attribute_name(:role)

      %th.ts-data-column-100
  %tbody
    - @users.each do |user|
      %tr
        %td
          = link_to user.email, user
        %td
          = user.approved
        - %i(sign_in_count current_sign_in_at last_sign_in_at current_sign_in_ip last_sign_in_ip created_at updated_at).each do |attribute|
          %td
            = user.public_send(attribute)
        %td
          = user.role.name
        %td
          = link_to t('views.application.buttons.show'), user, class: 'ts-button-show-slim'
          = link_to t('views.application.buttons.edit'), edit_user_path(user), class: 'ts-button-edit-slim'
          - if user.approved?
            = link_to t('views.application.buttons.toggle_unapprove'), toggle_approve_user_path(user), class: 'ts-button-toggle-unapprove-slim'
          - else
            = link_to t('views.application.buttons.toggle_approve'), toggle_approve_user_path(user), class: 'ts-button-toggle-approve-slim'
          - if user.removable?
            = link_to t('views.application.buttons.toggle_removable'), toggle_removable_user_path(user), class: 'ts-button-toggle-removable-slim'
          - else
            = link_to t('views.application.buttons.toggle_unremovable'), toggle_removable_user_path(user), class: 'ts-button-toggle-unremovable-slim'
          = link_to t('views.application.buttons.destroy'), user, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'ts-button-destroy-slim'

src/app/views/users/new.html.haml
%h1
  = User.model_name.human
= render 'form'

src/app/views/users/show.html.haml
%h1
  = User.model_name.human
  = format('"%s"', @user.email)

%section.ts-actions
  = link_to t('views.application.buttons.edit'), edit_user_path(@user), class: 'ts-button-edit'
  = link_to t('views.application.buttons.cancel'), users_path, class: 'ts-button-cancel', name: 'cancel'
  - if @user.approved?
    = link_to t('views.application.buttons.toggle_unapprove'), toggle_approve_user_path(@user), class: 'ts-button-toggle-unapprove'
  - else
    = link_to t('views.application.buttons.toggle_approve'), toggle_approve_user_path(@user), class: 'ts-button-toggle-approve'
  - if @user.removable?
    = link_to t('views.application.buttons.toggle_removable'), toggle_removable_user_path(@user), class: 'ts-button-toggle-removable'
  - else
    = link_to t('views.application.buttons.toggle_unremovable'), toggle_removable_user_path(@user), class: 'ts-button-toggle-unremovable'
  = link_to t('views.application.buttons.destroy'), @user, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'ts-button-destroy'

%table.ts-item-table
  - %i(email approved removable reset_password_sent_at sign_in_count current_sign_in_at last_sign_in_at current_sign_in_ip last_sign_in_ip created_at updated_at).each do |attribute|
    %tr
      %th
        = User.human_attribute_name(attribute)
      %td
        = @user.public_send(attribute)
  %tr
    %th
      = User.human_attribute_name(:role)
    %td
      = @user.role.name